### ISSUE TITLE
[przygotowanie danych] eurostat - wypadki

### ISSUE THREAD

**Issue by wsmolak** [wsmolak/amu_adp_final_proj#3]
Przygotowanie danych z eurostatu odnośnie wypadków w krajach UE.

KA:
* mamy dane nt. wypadków w krajach UE
* dane są gotowe do wyświetlenia na mapie oraz połączenia ze zbiorem odnośnie infrastruktury oraz pojazdów

**Comment by wsmolak** [comment]
1. znaki kodowania -> zmienić na UTF8
2. liczba wypadków na autostradach na 1000 km autostrady zamiast na 100k mieszkańców
BONUS - nice to have:
Widać, że kraje byłego bloku wschodniego mają najwyższy współczynnik wypadków. Ciekawe czy podobną średnią mają Niemcy Wschodnie. Super jakby się dało nanieść na mapę landy byłego NRD.

**Comment by mkarczewski85** [comment]
1. zrobione
2. zrobione
BONUS: pokazałem Niemcy na poziomie NUTS-2, szukałem historycznych map. Znalazłem bibliotekę cshape, ale nie ogarnąłem jeszcze jak jej używać.
